version: '3.8'

services:
  amnezia-monitor:
    build: .
    container_name: amnezia-monitor
    ports:
      - "8080:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - WG_INTERFACE=wg0
      - DB_PATH=data/monitor.db
    restart: always

