services:
  amnezia-monitor:
    build: .
    ports:
      - "8080:8000"
    volumes:
      # Пробрасываем папку /tmp с хост-машины внутрь контейнера
      - /tmp:/tmp
    environment:
      - AMNEZIA_CONTAINER_NAME=amnezia-awg
      - WG_INTERFACE=wg0
    restart: always